version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: link
      POSTGRES_PASSWORD: link
      POSTGRES_DB: link
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U link -d link"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      PORT: 8080
      STORAGE: memory
      DB_URL: postgres://link:link@postgres:5432/link?sslmode=disable

    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy